/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-06-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log  
 * Ver   Date         Author                               Modification
 * 1.0   03-16-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public  class BL_ICON_Constants {
   
    
    public static final String USE_CASE_APP_SETTING                       = 'App Settings';
    public static final String USE_CASE_CARE_SERVICES                     = 'Care_Services';
    public static final String USE_CASE_CARE_SERVICES_FULL                = 'Care_Services_Full'; 
    public static final String USE_CASE_CLIENT                            = 'Client';
    public static final String USE_CASE_CLIENTLISTMEMBERS                 = 'ClientListMembers';  
    public static final String USE_CASE_CLIENTMEMBERS                     = 'ClientMembers';
    public static final String USE_CASE_CLIENTMEMBERS_SERVICE             = 'ClientMembersService';
    public static final String USE_CASE_CLIENT_KPI                        = 'ClientKPI';
    public static final String USE_CASE_CLIENT_REQUEST                    = 'Client_Request';
    public static final String USE_CASE_CLIENT_REQUEST_FULL               = 'Client_Request_Full';
    public static final String USE_CASE_CUSTOM_CLIENTLIST                 = 'CustomClientList';
    public static final String USE_CASE_DASHBOARD                         = 'Dashboard';
    public static final String USE_CASE_EMAIL_TEMPLATE                    = 'Email Template';
    public static final String USE_CASE_EMAIL_TEMPLATE_FIELDS             = 'EmailTemplateFields';
    public static final String USE_CASE_EVENT                             = 'Event';
    public static final String USE_CASE_FIELD_MAPPINGS                    = 'Mapping';
    public static final String USE_CASE_INTERESTS                         = 'Interests';
    public static final String USE_CASE_KPI                               = 'KPI';
    public static final String USE_CASE_KPI_NEW                           = 'KPI New';
    public static final String USE_CASE_LOOK                              = 'Look';
    public static final String USE_CASE_LOOKSHARE                         = 'LookShare';
    public static final String USE_CASE_ONBOARDING                        = 'Onboarding';
    public static final String USE_CASE_PERMANENT_CLIENTLIST			  = 'PermanentClientList';
    public static final String USE_CASE_PURSHASE                          = 'Purchase';
    public static final String USE_CASE_PURCHASE_PRODUCT				  = 'Purchase Product';
    public static final String USE_CASE_RECENTLY_VIEWED                   = 'RecentlyViewed';
    public static final String USE_CASE_RECENTLY_VIEWED_CLIENT            = 'Recently Viewed Client';
    public static final String USE_CASE_SEARCH_CLIENT				      = 'searchClient';
    public static final String USE_CASE_SEARCH_CLIENT_SOQL				  = 'searchClient_SOQL';
    public static final String USE_CASE_SOCIAL_MEDIA_IDENTIFIER           = 'SocialMediaIdentifier';
    public static final String USE_CASE_SOCIAL_MEDIA_IDENTIFIER_BASIC     = 'SocialMediaIdentifier Basic';
    public static final String USE_CASE_STORE                             = 'Store';
    public static final String USE_CASE_SURVEY                            = 'Survey';
    public static final String USE_CASE_SURVEY_FULL                       = 'Survey_Full';
    public static final String USE_CASE_TASK                              = 'Task';
    public static final String USE_CASE_TASK_KPI                          = 'TaskKPI';
    public static final String USE_CASE_TEAM                              = 'Team';
    public static final String USE_CASE_TEAM_MEMBER						  = 'MemberTeam';
    public static final String USE_CASE_TODO_ASSISTANT                    = 'TodoAssistant';
    public static final String USE_CASE_USER                              = 'Me';
    public static final String USE_CASE_USER_EMP				          = 'User';
    public static final String USE_CASE_TAG     				          = 'Tag';
    public static final String USE_CASE_DEPOSIT     				      = 'Deposit';
    public static final String USE_CASE_NOTIFICATION     				  = 'Notification Item';
    public static final String USE_CASE_EXCLUSIVE     				      = 'Exclusive_Sale';
    public static final String USE_CASE_XSTORE_ORDERS_FULL    		      = 'XStore_Order_Full';
    public static final String USE_CASE_XSTORE_ORDERS          		      = 'XStore_Order';
    public static final String USE_CASE_NY_ORDERS    				      = 'NY_Order';
    public static final String USE_CASE_NY_ORDERS_FULL    				  = 'NY_Order_Full';
    public static final String USE_CASE_CONTENT_DOCUMENT    			  = 'ContentDocumentLink';
    public static final String USE_CASE_IDENTITY_USER    			  	  = 'IdentityUser';
    public static final String USE_CASE_EXCLUSIVE_OFFER   			  	  = 'Exclusive_Offer';
    public static final String USE_CASE_INTERACTIVE_WARDROBING   		  = 'Interactive_Wardrobing_Look';
    public static final String USE_CASE_RETENTION          			  	  = 'Retention';
    public static final String USE_CASE_PRODUCT_RECOMMENDATION            = 'ProductRecommendation';
    public static final String USE_CASE_CA_CONSENT                        = 'Ca_Consent';
    public static final String USE_CASE_CA_CONSENT_TEAM                   = 'Ca_Consent_Team';
    public static final String USE_CASE_COUNTRY_INFO                      = 'Country';
    public static final String USE_CASE_COUNTRY_LANGUAGE                  = 'CountryLanguage__c';
    public static final String USE_CASE_IW_CLIENT                         = 'IW_Client';
    public static final String USE_CASE_CLIENT_CAMPAIGN                   = 'Campaign';
    public static final String USE_CASE_VOICE_ANSWERS                     = 'Voice_Answers';
    public static final String USE_CASE_CLUB_MEMBER                       = 'Club_MemberShip';
	public static final String USE_CASE_COMMISSIONED_CA                   = 'CommissionedCA';


    //JSON_ROOT
    public static final String JSONRoot_outreaches                        ='outreaches';
    public static final String JSONRoot_appointments                      ='appointments';
    public static final String JSONRoot_appointmentsCount                 ='appointmentsCount';
    public static final String JSONRoot_purchasedProductsList             = 'purchasesProduct';
    public static final String JSONRoot_clientsContacted                  = 'clientsContacted';
    public static final String JSONRoot_countClientsContacted             = 'countClientsContacted';
    public static final String JSONRoot_tasksCount 				          = 'tasksCount';
    public static final String JSONRoot_appointmentsToComeCount 	      = 'appointmentsToComeCount';
    public static final String JSONRoot_appointmentsToCome 	              = 'appointmentsToCome';
    public static final String JSONRoot_appointmentsWithPurchaseCount 	  = 'appointmentsWithPurchaseCount';
    public static final String JSONRoot_myWardrobingTasksCount	          = 'wardrobingOutreach';
    public static final String JSONRoot_currency 	                      = 'currency';
    public static final String JSONRoot_my10K 	                          = 'my10k';
    public static final String JSONRoot_myPotential10K			          = 'myPotential10K';
    public static final String JSONRoot_myConfirmed10K                    = 'myConfirmed10K';
    public static final String JSONRoot_myConfirmed50K                    = 'myConfirmed50K';
    public static final String JSONRoot_myClients10K 	                  = 'myClients10k';
    public static final String JSONRoot_my10KLifestyle                    = 'my10KLifestyle';
    public static final String JSONRoot_myClientsPotential10K			  = 'myClientsPotential10k';
    public static final String JSONRoot_myClientsConfirmed10K             = 'myClientsConfirmed10k';
    public static final String JSONRoot_myClientsConfirmed50K             = 'myClientsConfirmed50k';
	public static final String JSONRoot_myClients10KLifestyle             = 'myClients10kLifestyle';
    public static final String JSONRoot_myClientsConfirmed50KYTD          = 'myClientsConfirmed50KYTD';
    public static final String JSONRoot_myConfirmed50KYTD                 = 'myConfirmed50KYTD';
}