public with sharing class BL_Experiences_Constants {

    
    public static final String USE_CASE_EXPERIENCE = 'Experience';
    public static final String USE_CASE_EXPERIENCE_VARIATION = 'Experience_Variation';
    public static final String USE_CASE_EXPERIENCE_VARIATION_MEMBER = 'Experience_Variation_Member';
    public static final String USE_CASE_EXPERIENCE_VARIATION_GUEST = 'Experience_Variation_Guest';
    public static final String USE_CASE_EXPERIENCE_VARIATION_APPOINTMENT = 'Appointment';
    public static final String USE_CASE_EXPERIENCE_VARIATION_EVITE = 'Experience_Variation_Evite';
    public static final String USE_CASE_EXPERIENCE_VARIATION_MEMBER_STATUS = 'Experience_Variation_Member_Status';




    public static final String JSONRoot_clientsNominatedNumber                  = 'clientsNominatedNumber';
    public static final String JSONRoot_clientsNotRegisteredNumber              = 'clientsNotRegisteredNumber';
    public static final String JSONRoot_clientsConfirmedNumber                  = 'clientsConfirmedNumber';
    public static final String JSONRoot_clientsDeclinedNumber                   = 'clientsDeclinedNumber';
    public static final String JSONRoot_clientsFillAttendanceNumber 	        = 'clientsFillAttendanceNumber';
    public static final String JSONRoot_clientsParticipatedNumber               = 'clientsParticipatedNumber';
    public static final String JSONRoot_clientsNotParticipatedNumber 	        = 'clientsNotParticipatedNumber';

}