public class AsyncSO_WS_RMS_SalesCreation_v3 {
    // public class mainServiceResponseFuture extends System.WebServiceCalloutFuture {
    //     public SO_WS_RMS_SalesCreation_v3.salesCreationResponse getValue() {
    //         SO_WS_RMS_SalesCreation_v3.mainServiceResponse response = (SO_WS_RMS_SalesCreation_v3.mainServiceResponse)System.WebServiceCallout.endInvoke(this);
    //         return response.salesCreationResponse;
    //     }
    // }
    // public class AsyncWSLV003_webService_v3_0_salesCreation_Port_2 {
    //     public String endpoint_x = 'https://zlvcp086d:11803/ws/WSLV003.webService.v3_0:salesCreation';
    //     public Map<String,String> inputHttpHeaders_x;
    //     public String clientCertName_x;
    //     public Integer timeout_x;
    //     private String[] ns_map_type_info = new String[]{'http://zlvcp086d/WSLV003/webService/v3_0/salesCreation', 'SO_WS_RMS_SalesCreation_v3'};
    //     public AsyncSO_WS_RMS_SalesCreation_v3.mainServiceResponseFuture beginMainService(System.Continuation continuation,SO_WS_RMS_SalesCreation_v3.salesCreation salesCreation) {
    //         SO_WS_RMS_SalesCreation_v3.mainService request_x = new SO_WS_RMS_SalesCreation_v3.mainService();
    //         request_x.salesCreation = salesCreation;
    //         return (AsyncSO_WS_RMS_SalesCreation_v3.mainServiceResponseFuture) System.WebServiceCallout.beginInvoke(
    //           this,
    //           request_x,
    //           AsyncSO_WS_RMS_SalesCreation_v3.mainServiceResponseFuture.class,
    //           continuation,
    //           new String[]{endpoint_x,
    //           'WSLV003_webService_v3_0_salesCreation_Binder_2_mainService',
    //           'http://zlvcp086d/WSLV003/webService/v3_0/salesCreation',
    //           'mainService',
    //           'http://zlvcp086d/WSLV003/webService/v3_0/salesCreation',
    //           'mainServiceResponse',
    //           'SO_WS_RMS_SalesCreation_v3.mainServiceResponse'}
    //         );
    //     }
    // }
}