/**
* This is a webservice mock class for :
* AsyncSO_WS_RMS_ClientEnquiryV3
* AsyncSO_WS_RMS_ClientSearchV3
* AsyncSO_WS_RMS_SalesCreation_v3
* AsyncSO_WS_RMS_SaleServices
* AsyncWS019_CreateDeposit
* SO_WS_RMS_Async_ProductSearch

* @createdBy           Calev Machiah, 11-08-2022
* @lastModifiedBy      Calev Machiah, 11-08-2022
*/

// @isTest
 public class AsyncSO_WS_RMS_Mock //implements WebServiceMock
  { // MIY-2154
//   public void doInvoke(
//           Object stub,
//           Object request,
//           Map<String, Object> response,  
//           String endpoint,
//           String soapAction,
//           String requestName,
//           String responseNS,
//           String responseName,
//           String responseType) {
//         // try{
//         // AsyncWS019_CreateDeposit.salesCreationFromNYResponseFuture async3 = new AsyncWS019_CreateDeposit.salesCreationFromNYResponseFuture();
//         // WS019_CreateDeposit.salesCreationResponse resp3 = async3.getValue();
//         // }
//         // catch(Exception e){system.debug('error :' + e);}
         
//         // try{      
//         // AsyncSO_WS_RMS_ClientSearchV3.mainServiceResponseFuture async1 = new AsyncSO_WS_RMS_ClientSearchV3.mainServiceResponseFuture();
//         // SO_WS_RMS_ClientSearchV3.clientSearchResponse resp1 = async1.getValue();
//         // }
//         // catch(Exception e){system.debug('error :' + e);}
            
//         // try{
//         // AsyncSO_WS_RMS_SalesCreation_v3.mainServiceResponseFuture async2 = new AsyncSO_WS_RMS_SalesCreation_v3.mainServiceResponseFuture();
//         // SO_WS_RMS_SalesCreation_v3.salesCreationResponse resp2 = async2.getValue();
//         // }
//         // catch(Exception e){system.debug('error :' + e);}
            
//         try{
//         AsyncSO_WS_RMS_SaleServices.mainServiceResponseFuture async4 = new AsyncSO_WS_RMS_SaleServices.mainServiceResponseFuture();
//       //  SO_WS_RMS_SalesCreation_v3.salesCreationResponse resp4 = async4.getValue();
//         }
//         catch(Exception e){system.debug('error :' + e);}
            
//         // try{    
//         // AsyncSO_WS_RMS_ClientEnquiryV3.mainServiceResponseFuture async5 = new AsyncSO_WS_RMS_ClientEnquiryV3.mainServiceResponseFuture();
//         // SO_WS_RMS_ClientEnquiryV3.clientDetailEnquiryResponse resp5 = async5.getValue();
//         // }
//         // catch(Exception e){system.debug('error :' + e);}
            
//         // try{    
//         // SO_WS_RMS_Async_ProductSearch.mainServiceResponseFuture mainServiceResponseFuture = new SO_WS_RMS_Async_ProductSearch.mainServiceResponseFuture();
//         // SO_WS_RMS_ProductSearch.itemSearchResponse itemSearchResponse = mainServiceResponseFuture.getValue(); 
//         // }
//         // catch(Exception e){system.debug('error :' + e);}

//   }
}