import { createElement } from 'lwc';
import Icx_orderShippingTileKit from 'c/icx_orderShippingTileKit';

describe('c-icx-order-shipping-tile-kit', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-icx-order-shipping-tile-kit', {
            is: Icx_orderShippingTileKit
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});