public with sharing class BL_EMAIL_Constants {

    public static final String USE_CASE_ADDRESSES                   = 'OrgWideEmailAddress';
    public static final String USE_CASE_EMAIL_TEMPLATE              = 'Email Template';
    public static final String USE_CASE_EMAIL_TEMPLATE_DETAILS      = 'Email Template Details';
    public static final String USE_CASE_SEARCH_CLIENT               = 'SearchContactClient';
    public static final String USE_CASE_SEARCH_USER                 = 'SearchContactUser';
    public static final String USE_CASE_EMAIL_CONFIGURATOR          = 'EmailConfigurator';
    public static final String USE_CASE_CONTENT_VERSION             = 'ContentVersion';
    public static final String USE_CASE_FOLDER                      = 'Folder';
    public static final String USE_CASE_QUICK_TEXT                  = 'QuickText';
    public static final String USE_CASE_ACCOUNT_FIELDS              = 'UC_AccountEmail';
    public static final String USE_CASE_REQUEST_FIELDS              = 'UC_RequestEmail';
    public static final String USE_CASE_CARESERVICE_FIELDS          = 'UC_RepairEmail';
    public static final String USE_CASE_FAMILY_FIELDS               = 'UC_FamilyEmail';
    public static final String USE_CASE_ICONICS_SETTINGS            = 'ICONICS_Settings';
    public static final String USE_CASE_EMAIL_TYPE                  = 'Email Type';
    public static final String USE_CASE_TASK_FIELDS                 = 'Task';
    public static final String USE_CASE_EMAIL_MESSAGE_FIELDS        = 'UC_EmailMessageEmail';

    public static final String JSONRoot_EmailTemplate       = 'emailTemplate';
    public static final String JSONRoot_SenderAddresses     = 'senderAddresses';
}