name: Metadata Duplicate Check
run-name: ${{ github.actor }} is launching | Metadata Duplicate Check 🔍

on:
  workflow_call:
    inputs:
      directories:
        required: true
        type: string

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: true
          ref: ${{ github.head_ref }}

      - name: Check for duplicate files
        run: |
          directories="${{ inputs.directories }}"  # Access the passed input
          declare -A file_map
          duplicates=""
          
          echo $file_map
          # Combine all directories into a single find command
          while IFS= read -r -d '' file; do
            # Extract the relative path of the file
            relative_path="${file#*/}"
            relative_path="${relative_path#*/}"
            echo $relative_path

            # Skip files that contain 'gitkeep' in the path
            if [[ "$relative_path" == *gitkeep* ]]; then
              continue
            fi

            if [[ -n ${file_map[$relative_path]} ]]; then
              duplicates+="<==> $file is a duplicate of ${file_map[$relative_path]}"$'\n'
            else
              file_map[$relative_path]=$file
            fi
          done < <(find $directories -type f -print0)

          # Output results
          if [[ -n "$duplicates" ]]; then
            echo "Duplicate files detected:" > duplicate.log
            echo "$duplicates" >> duplicate.log
            echo "Duplicate files detected. See duplicate.log for details."
            cat duplicate.log
            exit 1
          else
            echo "No duplicate files found." > duplicate.log
            echo "No duplicate files found."
            cat duplicate.log
          fi

      - name: Upload duplicate.log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: duplicate-log
          path: duplicate.log
