name: INTEGRATION VALIDATE
run-name: ${{ github.actor }} | INTEGRATION VALIDATE from ${{ github.base_ref }} 🚀

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'int-ww'
      - 'int-common'
      - 'int-cn'
  workflow_dispatch:

jobs:

  INT_validate_only_ww:
    if: github.base_ref == 'int-ww' ||  github.base_ref == 'int-common'
    uses: './.github/workflows/salesforce_job.yml'
    with:
      environment: 'INT-WW'
      generate_delta: true
      validate_only: true
      target: ${{ github.base_ref }}
    secrets:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

  INT_validate_only_cn:
    if: github.base_ref == 'int-cn' ||  github.base_ref == 'int-common'
    uses: './.github/workflows/salesforce_job.yml'
    with:
      environment: 'INT-CN'
      generate_delta: true
      validate_only: true
      target: ${{ github.base_ref }}
    secrets:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

