name: Salesforce Job

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      generate_delta:
        required: true
        type: boolean
      validate_only:
        required: true
        type: boolean
  workflow_dispatch:    

jobs:
  run:
    runs-on: compose-self-hosted
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install 

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Authenticate with Salesforce Org
        run: |  
          echo "force://${{ vars.CONSUMER_KEY }}::${{ vars.REFRESH_TOKEN}}@${{ vars.INSTANCE_URL}}" > ./SFDX_URL.txt                       
          sfdx force:auth:sfdxurl:store -f ./SFDX_URL.txt --setalias ${{ vars.ALIAS}} --setdefaultusername

      - name: Generate DELTA for validation
        if: ${{ inputs.generate_delta && inputs.validate_only }}
        run: | 
          node sf-delta/index.js --projectPath sfoa --baseBranch ${{ vars.TARGET_DIFF }}..HEAD
          node sf-delta/index.js --projectPath force-app --baseBranch ${{ vars.TARGET_DIFF }}..HEAD

      - name: Generate DELTA for deployment
        if: ${{ inputs.generate_delta && !inputs.validate_only }}
        run: | 
          node sf-delta/index.js --projectPath sfoa --baseBranch ${{ vars.TARGET_DIFF }}..HEAD^
          node sf-delta/index.js --projectPath force-app --baseBranch ${{ vars.TARGET_DIFF }}..HEAD^


      - name: Validate to Salesforce (Check Only)
        if: ${{ inputs.validate_only }}
        run: |
          if [ -f "delta/main/default/package.xml" ]; then
            if [[ "${{ inputs.environment }}" == *"STAGING"* ]]; then
              sfdx force:source:deploy --sourcepath delta/main/default --checkonly --targetusername ${{ vars.ALIAS }} --verbose --testlevel RunAllTestsInOrg
            else
              sfdx force:source:deploy --sourcepath delta/main/default --checkonly --targetusername ${{ vars.ALIAS }} --verbose
            fi
          else
            echo "The DELTA does not exist. Nothing to validate"
          fi

      - name: Deploy to Salesforce
        if: ${{ !inputs.validate_only }}
        run: |
          if [ -f "delta/main/default/package.xml" ]; then
            sfdx force:source:deploy --sourcepath delta/main/default --targetusername ${{ vars.ALIAS }} --verbose
          else
            echo "The DELTA does not exist. Nothing to deploy"
          fi
