name: STAGING VALIDATE
run-name: ${{ github.actor }} | STAGING VALIDATE 🚀

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'staging-ww'
      - 'staging-common'
      - 'staging-cn'
  workflow_dispatch:

jobs:
  PPROD_validate_only_ww:
    if: github.base_ref == 'staging-ww' || github.base_ref == 'staging-common'
    uses: './.github/workflows/salesforce_job.yml'
    with:
      environment: 'STAGING-WW'
      generate_delta: true
      validate_only: true
    secrets:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

  PPROD_validate_only_cn:
    if: github.base_ref == 'staging-cn' || github.base_ref == 'staging-common'
    uses: './.github/workflows/salesforce_job.yml'
    with:
      environment: 'STAGING-CN'
      generate_delta: true
      validate_only: true
    secrets:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
